#!/bin/bash

# module load singularity

export SINGULARITY_CACHEDIR="/data1/shahs3/users/vazquezi/projects/spectrum/cache"
export SINGULARITY_TMPDIR="/data1/shahs3/users/vazquezi/projects/spectrum/tmp"

# Run snakemake
snakemake \
	--keep-going \
	--printshellcmds \
	--latency-wait 10 \
	--rerun-incomplete \
	--jobs 5000 \
	--shadow-prefix "/data1/shahs3/users/vazquezi/projects/spectrum/cache" \
	--use-singularity \
	--singularity-args "-B /usersoftware -B /data1 -B /home/vazquezi" \
	--singularity-prefix /data1/shahs3/users/vazquezi/projects/spectrum/.singularity \
	--reason \
	--cluster-config cluster_slurm.json \
	--cluster "sbatch --partition={cluster.partition} --nodes=1 --ntasks=1 --cpus-per-task={cluster.threads} --time={cluster.time} --mem-per-cpu={cluster.mem-per-cpu} --output=logs/snakemake_%j.log" #\
	# --js jobscript.sh \
	# --slurm \
	# --default-resources #slurm_account={cluster.account} slurm_partition={cluster.partition}
